<?php

namespace Database\Seeders;

use App\Enums\ProductType;
use App\Enums\ProductUnit;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        $defaults = [];

        foreach ($this->products() as $row) {
            Product::create(array_merge($defaults, $row));
        }
    }

    private function products(): array
    {
        return [
            [
                'uid' => 'RD.W1110.0000.1000',
                'name' => 'Wolturnus rolstoel type W5 original',
                'description' => "ZB= 45\nZD= 47\nRH= 34\nZH-VOOR= 52\nZH-ACHTER= 46",
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Frame,
                'company_sales_price' => 3512.63,
                'company_purchase_price' => 878.16,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W6190.0000.1509',
                'name' => 'Frame rolstoel/handbike brons geanodiseerd',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W6110.0000.0001',
                'name' => 'Verstelbare achteras',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W6100.0000.0001',
                'name' => 'Ergonomische zit',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 179.55,
                'company_purchase_price' => 44.89,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W6120.0000.0009',
                'name' => 'Voorzijde frame U V vorm',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8861.1010.1300',
                'name' => 'Anti-tip wegzwenkbaar',
                'description' => 'RECHTS',
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 248.68,
                'company_purchase_price' => 62.17,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8131.0000.1006',
                'name' => 'Vaste rugleuning, gelast',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8122.0020.0112',
                'name' => 'ILSA lateraal verstelbare (STD) rugbuizen Ø25',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 406.00,
                'company_purchase_price' => 101.50,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8219.0015.0000',
                'name' => 'Voetsteun hoogte verstelbaar',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8299.9901.0003',
                'name' => 'Voetplaat naar achteren opklapbaar',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 380.37,
                'company_purchase_price' => 95.09,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8350.9921.0001',
                'name' => 'Rubber grip op voetplaat',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 47.05,
                'company_purchase_price' => 11.76,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W7100.0000.0000',
                'name' => 'Zitbespanning compleet',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W7100.0000.0001',
                'name' => 'Rugbespanning compleet',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W7100.0000.2501',
                'name' => 'meerprijs voor brede rugflap',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 17.51,
                'company_purchase_price' => 4.38,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W7100.9999.0001',
                'name' => 'Hoekstukken rugbekleding uitgevoerd in zwart leer',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RDRE.EB.LR.01',
                'name' => 'Eagle Brake alu schaarrem zwart',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 142.97,
                'company_purchase_price' => 35.74,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8810.0030.0000',
                'name' => 'Carbon zijschotten met spatbescherming',
                'description' => 'VASTGESCHROEFD',
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 606.83,
                'company_purchase_price' => 151.71,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8131.0005.0003',
                'name' => 'Duwhandvatten Ø25 in hoogte verst. (versterkt tbv tillen)',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 380.37,
                'company_purchase_price' => 95.09,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8870.0020.0001',
                'name' => 'Taxifixatie tbv 4-punt bev.',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 358.95,
                'company_purchase_price' => 89.74,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8600.1020.1405',
                'name' => 'Alu Froglegs softroll 4"',
                'description' => 'ZILVER',
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 235.08,
                'company_purchase_price' => 58.77,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8510.2250.1009',
                'name' => 'standaard 25" wielen',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RDHO.CA.GEKN25b',
                'name' => 'Carbolife Gekko (normaal) zilver hoepel 25"',
                'description' => 'MONTEREN OP OUDE WIELEN',
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 414.16,
                'company_purchase_price' => 103.54,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W9662.2501.0002',
                'name' => 'Schwalbe Marathon+ 25"',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 66.66,
                'company_purchase_price' => 16.67,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8250.0000.0007',
                'name' => 'verstevigde Stabilisatiebuis tbv handbikemontage',
                'description' => 'ROAM WORDT NIET DOOR RD GEMONTEERD',
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 89.54,
                'company_purchase_price' => 22.39,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RDKU.BASIS',
                'name' => 'EP kussen met onderstaande samenstelling:',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 84.03,
                'company_purchase_price' => 21.01,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RDKU.PA05H',
                'name' => 'koudschuim, Pantera 5cm, hard',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 18.56,
                'company_purchase_price' => 4.64,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RDKU.VL02',
                'name' => 'vlokschuim 2cm',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 10.88,
                'company_purchase_price' => 2.72,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RDKH.INCO',
                'name' => 'extra Incontinentiehoes (dartex) tbv kussen',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 75.58,
                'company_purchase_price' => 18.90,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RDKU.HO.ME',
                'name' => 'Mesh stof tbv kussen',
                'description' => null,
                // 'qty' => 1.00,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Part,
                'company_sales_price' => 31.03,
                'company_purchase_price' => 7.76,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.W8510.2250.1009',
                'name' => 'standaard 25" wielen',
                'description' => "EXTRA WIEL INCL. BAND EN\nHOEPEL ALS RESERVE\nMEEGELEVERD",
                // 'qty' => 0.50,
                'unit' => ProductUnit::Set,
                'type' => ProductType::Part,
                'company_sales_price' => 0.00,
                'company_purchase_price' => 0.00,
                'company_margin' => 0.00,
                'supplier_id' => random_int(1, 3),
            ],
            [
                'uid' => 'RD.ARB.LOC',
                'name' => 'arbeid op locatie',
                'description' => null,
                // 'qty' => 0.50,
                'unit' => ProductUnit::Pieces,
                'type' => ProductType::Service,
                'company_sales_price' => 84.20,
                'company_purchase_price' => 21.05,
                'company_margin' => 25.00,
                'supplier_id' => random_int(1, 3),
            ],
        ];
    }
}
